### ISSUE TITLE
Merge the core library with the test support library 

### ISSUE THREAD

**Issue by mbrandonw** [pointfreeco/swift-composable-architecture#70]
(NB: This issue subsumes https://github.com/pointfreeco/swift-composable-architecture/issues/57 and https://github.com/pointfreeco/swift-composable-architecture/issues/60)

Due to an SPM/Xcode bug we cannot have separate `ComposableArchitecture` and `ComposableArchitectureTestSupport` libraries. The bug is that SPM packages cannot vend two libraries where one depends on the other. The bug manifests itself by simply not compiling (if you split your app into multiple modules), or crashing the test suite (this happens most often on iOS 11.3, as seen in #52).

We've tried our hardest to work around this bug, but each thing we do seems to just cause another problem.

So, until the bug is fixed we have two options:

* Split the test support library into own repository 
* Combine the test support code into the core library

The first option is a non-starter for us because it would be quite an extra burden for us to maintain two libraries that need parallel releases, and it would complicate how we structure the example apps in this repo.

The second option seems possible, but we are not sure how to accomplish it. The problem is that we can't put any `XCTest` code inside `ComposableArchitecture` since the library is meant to be deployed to devices. Fortunately, we are only using one single symbol from `XCTest`, and that is `XCTFail`. We've spent a few hours trying to figure out if it's possible to dynamically invoke `XCTFail` without importing `XCTest` or mentioning the symbol, but everything we've tried has come up short (including using `dlopen` and `dlsym` 😬).

Does anyone have any ideas on a path forward?

**Comment by natemann** [comment]
This probably won't help, but how does RxSwift import RxTest into their SPM. I looked at their package.swift file, and it doesn't seem like they are doing anything special

**Comment by stephencelis** [comment]
RxSwift has the same problem unfortunately 😞 @freak4pc may be able to offer more context.

**Comment by freak4pc** [comment]
@natemann We indeed are facing the same issue and I have an open bug about this: 
https://bugs.swift.org/browse/SR-12303

Basically SPM, in a test target, would import the core (RxSwift) once for the app, and once for RxTest (e.g. the test target), which causes symbol duplication, etc. You can get it to compile by forcing "dynamic", but then you would simply get a runtime crash. 

This is really a massive issue with SPM that I'm unsure of why it's not getting higher priority. This isn't a niche use case, basically any framework that has a separate testing framework for its use-case can't use SPM. I imagine there are some hacks but I didn't find something that works well enough, yet. 

Moving the test library into the core library isn't a valid solution in my case. It might also motivate people to use test-only code/hacks in actual production code. 

If I'd do it, I'd do it only for SPM for our case.

**Comment by natemann** [comment]
@freak4pc, thanks, and this is surprising. I have a workspace with multiple local SPMs that import RxSwift and RxTest. Everything runs correctly as far as I know. I get no crashes, and all tests run. I am using version 5.0.0

**Comment by freak4pc** [comment]
> @freak4pc, thanks, and this is surprising. I have a workspace with multiple local SPMs that import RxSwift and RxTest. Everything runs correctly as far as I know. I get no crashes, and all tests run. I am using version 5.0.0

Very interesting. Is this Xcode 11.4.1?

**Comment by natemann** [comment]
@freak4pc version 11.3. 11.4.1 is not working for other reasons (realm)

**Comment by freak4pc** [comment]
> @freak4pc version 11.3. 11.4.1 is not working for other reasons (realm)

It could be a possible regression between these versions. If you get a chance to try some portion of it on 11.4.1 and it works for some weird reason, I’d love to know :)

**Comment by natemann** [comment]
@freak4pc, I will see what I can do. 11.4.1 was not working earlier, but it did not seem to be due to RxSwift.

**Comment by antranapp** [comment]
I can confirm this is 11.4.1 issue. I had no problem with integrating RxSwift using SPM in the previous versions of Xcode

**Comment by natemann** [comment]
in 11.4.1, I can run each package's test separately, and it works. But when I try to run tests for the entire workspace, that includes the tests for each package, it does not work

**Comment by stephencelis** [comment]
After a few hours of very wild research we landed on something that seems to work: https://github.com/pointfreeco/swift-composable-architecture/pull/71

Can anyone who's been having issues check out this branch and give things a spin?

**Comment by freak4pc** [comment]
So you did end up putting it In the same target ?

**Comment by stephencelis** [comment]
> So you did end up putting it In the same target ?

We did. We realize this may not be a solution for RxSwift but in our case it is more convenient and only leaks a single module-level type (`TestStore`), which is also hidden behind a `DEBUG` flag, so it shouldn't leak into release builds.

**Comment by darrarski** [comment]
After change introduced in #71, I am no longer able to use the library in my project.

I have the following setup:

target|description
:--|:--
MyApp|main iOS app target
MyFramework|iOS framework target

MyApp depends on MyFramework. I would like to use ComposableArchitecure in both targets. However, if I integrate it via SPM in Xcode, I got this compilation error:

> Swift package product 'ComposableArchitecture' is linked as a static library by 'MyApp' and 'MyFramework'. This will result in duplication of library code.

I guess the reason behind this error is [removal of `type: .dynamic` parameter](https://github.com/pointfreeco/swift-composable-architecture/pull/71/files#diff-37ca2dd15ca0f6b1b49e78db084ef5b9L16) in Package.swift.

**Comment by stephencelis** [comment]
@darrarski Sorry about the confusion! Apple recommends creating a single framework to house all of your static dependencies and _this_ would be the dynamic library you could share among all of your repos.

The Tic-Tac-Toe demo app sets this example by defining a TicTacToeCommon framework and it is the _only_ framework that links to ComposableArchitecture. Every other target embeds TicTacToeCommon to gain access to ComposableArchitecture.

**Comment by darrarski** [comment]
Thanks @stephencelis for the quick reply! I will definitely check the example integration. I appreciate your support, and I am sure the library will become a big thing in iOS development 🚀
