### ISSUE TITLE
ViewStore binding provided as `NavigationStack` path gives fatal error on back navigation with 0.48.0, not 0.47.2

### ISSUE THREAD

**Issue by sebj** [pointfreeco/swift-composable-architecture#1798]
### Description

After updating from 0.47.2 to 0.48.0, a ViewStore binding provided as the `path` to a SwiftUI `NavigationStack` will now result in a crash when navigating to a screen and then pressing the back button.

The error is:
```
Swift/RangeReplaceableCollection.swift:902: Fatal error: Can't remove more items from a collection than it contains
```

I can reliably reproduce this in a [brand new minimal project](https://gist.github.com/sebj/524c207ffb4057f157eab7dc0b9d499d) with Composable Architecture as an SPM dependency, where 0.48.0 (and also `main` branch @ `30015d1`) crashes and switching to 0.47.2 (and back and forth) does not in this situation.

It's totally possible this isn't a regression and I'm doing something wrong here, would love to know if so 😅 

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

Navigating to a screen, and then pressing the Back button navigates back successfully (does not crash)

### Actual behavior

A fatal error occurs.

### Steps to reproduce

1. Add the following Gist contents to a new project with Composable Architecture as an SPM dependency: https://gist.github.com/sebj/524c207ffb4057f157eab7dc0b9d499d
2. Tap 'Go to A' or 'Go to B'
3. Tap '< Back' to go back
4. Observe fatal error

### The Composable Architecture version information

0.48.0 & `main` @ `30015d1`

### Destination operating system

iOS 16

### Xcode version information

Version 14.2 (14C18)

### Swift Compiler version information

```shell
swift-driver version: 1.62.15 Apple Swift version 5.7.1 (swiftlang-5.7.1.135.3 clang-1400.0.29.51)
Target: arm64-apple-macosx13.0
```
