### ISSUE TITLE
Is visionOS a supported SDK for TCA?

### ISSUE THREAD

**Issue by peterbohac** [pointfreeco/swift-composable-architecture#2745]
### Description

Hi. I've got (several internal) visionOS projects using TCA. We just updated to TCA 1.7.1 and it appears to be broken with:
```
~/Library/Developer/Xcode/DerivedData/StrykerUI-faynflhfddowpfaglyxkrocatcqx/SourcePackages/checkouts/swift-composable-architecture/Sources/ComposableArchitecture/Observation/Binding+Observation.swift:198:10: error: '_StoreBindable_Perception' is unavailable in visionOS
    ) -> _StoreBindable_Perception<State, Action, Member> {
         ^~~~~~~~~~~~~~~~~~~~~~~~~
~/Library/Developer/Xcode/DerivedData/StrykerUI-faynflhfddowpfaglyxkrocatcqx/SourcePackages/checkouts/swift-composable-architecture/Sources/ComposableArchitecture/Observation/Binding+Observation.swift:192:17: note: '_StoreBindable_Perception' was obsoleted in iOS 17
  public struct _StoreBindable_Perception<State: ObservableState, Action, Value> {
                ^
~/Library/Developer/Xcode/DerivedData/StrykerUI-faynflhfddowpfaglyxkrocatcqx/SourcePackages/checkouts/swift-composable-architecture/Sources/ComposableArchitecture/Observation/Binding+Observation.swift:35:7: error: '_StoreBindable_Perception' is unavailable in visionOS
      _StoreBindable_Perception(bindable: self, keyPath: keyPath)
      ^~~~~~~~~~~~~~~~~~~~~~~~~
~/Library/Developer/Xcode/DerivedData/StrykerUI-faynflhfddowpfaglyxkrocatcqx/SourcePackages/checkouts/swift-composable-architecture/Sources/ComposableArchitecture/Observation/Binding+Observation.swift:192:17: note: '_StoreBindable_Perception' was obsoleted in iOS 17
  public struct _StoreBindable_Perception<State: ObservableState, Action, Value> {
                ^
~/Library/Developer/Xcode/DerivedData/StrykerUI-faynflhfddowpfaglyxkrocatcqx/SourcePackages/checkouts/swift-composable-architecture/Sources/ComposableArchitecture/Observation/Binding+Observation.swift:199:7: error: '_StoreBindable_Perception' is unavailable in visionOS
      _StoreBindable_Perception<State, Action, Member>(
      ^~~~~~~~~~~~~~~~~~~~~~~~~
~/Library/Developer/Xcode/DerivedData/StrykerUI-faynflhfddowpfaglyxkrocatcqx/SourcePackages/checkouts/swift-composable-architecture/Sources/ComposableArchitecture/Observation/Binding+Observation.swift:192:17: note: '_StoreBindable_Perception' was obsoleted in iOS 17
  public struct _StoreBindable_Perception<State: ObservableState, Action, Value> {
                ^
```

These projects all compile fine with TCA 1.7.0.

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

TCA frameworks should build without error using latest public visionOS SDK.

### Actual behavior

TCA framework fails to build successfully.

### The Composable Architecture version information

1.71

### Destination operating system

visionOS 1.0

### Xcode version information

Version 15.2 (15C500b)

### Swift Compiler version information

```shell
swift-driver version: 1.87.3 Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
Target: arm64-apple-macosx14.0
```

**Comment by peterbohac** [comment]
This PR is likely not the correct solution, but it does fix the issue for me: https://github.com/pointfreeco/swift-composable-architecture/pull/2746

**Comment by stephencelis** [comment]
Closed by #2746.
