### ISSUE TITLE
BindingAction - Type 'WritableKeyPath<Root, Value>' does not conform to the 'Sendable' protocol @ XCode 26.4

### ISSUE THREAD

**Issue by mercadodiego** [pointfreeco/swift-composable-architecture#3899]
### Description

On Xcode 26.4 and swift-compossable-architecture version as 1.25.2, at file `swift-composable-architecture/Sources/ComposableArchitecture/Observation/Binding+Observation.swift:`, I'm getting the `Type 'WritableKeyPath<Root, Value>' does not conform to the 'Sendable' protocol` compilation error on line 86

```
extension BindingAction {
  public static func set<Value: Equatable & Sendable>(
    _ keyPath: _SendableWritableKeyPath<Root, Value>,
    _ value: Value
  ) -> Self where Root: ObservableState {
    .init(
      keyPath: keyPath,
      set: { $0[keyPath: keyPath] = value },
      value: value,
      valueIsEqualTo: { $0 as? Value == value }
    )
  }

  public static func ~= <Value>(
    keyPath: WritableKeyPath<Root, Value>,
    bindingAction: Self
  ) -> Bool where Root: ObservableState {
    keyPath == bindingAction.keyPath
  }
}
```

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [x] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-composable-architecture/issues) or [discussion](https://github.com/pointfreeco/swift-composable-architecture/discussions).

### Expected behavior

It should compile fine on XCode 26.3

### Actual behavior

I'm getting 

### Reproducing project

On Xcode 26.4 and swift-compossable-architecture version as 1.25.2, at file `swift-composable-architecture/Sources/ComposableArchitecture/Observation/Binding+Observation.swift:`, I'm getting the `Type 'WritableKeyPath<Root, Value>' does not conform to the 'Sendable' protocol` compilation error on line 86

### The Composable Architecture version information

1.25.2

### Destination operating system

iOS 26.1

### Xcode version information

Version 26.4 (17E192)

### Swift Compiler version information

```shell
swift-driver version: 1.148.6 Apple Swift version 6.3 (swiftlang-6.3.0.123.5 clang-2100.0.123.102)
Target: arm64-apple-macosx26.0
```

**Comment by stephencelis** [comment]
@mercadodiego I'm able to compile things in the newly release Xcode 26.4 just fine. Can you share a project (with Package.resolved file) that reproduces the issue? Or maybe clean things and try again?

**Comment by mercadodiego** [comment]
Thanks for the quick answer @stephencelis . Let me check!

**Comment by mercadodiego** [comment]
It was a cache error. After some cleanup and adding/removing libraries, it finally went through. Thanks for your feedback!!

**Comment by taemon565** [comment]
Ошибка все еще воспроизводится после обновления до xcode 24.3. Очистка кеша, удаление ДД, добавление/удаление библиотеки и переустановка xcode не помогает.

**Comment by usa4060** [comment]
@stephencelis 
I also experienced the same phenomenon in the automatic deployment environment through Xcode Cloud.
So now, I lowered the Xcode version of Xcode Cloud to 26.1, so it's working normally
```
Type 'WritableKeyPath<Root, BindingState<Value>>' does not conform to the 'Sendable' protocol

Binding.swift:235
```

**Comment by stephencelis** [comment]
@mercadodiego Looks like you may have accidentally reopened this. Closing it since you didn't comment with new info, but if you meant to reopen, please include a comment as to why and what we should look into.

**Comment by mercadodiego** [comment]
HI @stephencelis I did it because other users were experimenting similar issues. But for me it's finally working. So If you'd like I can close it definitely.
