### PR TITLE
Xcode 26.4 fixes

### PR DESCRIPTION
**Pull request by stephencelis**
Still some warnings to tackle later, but this gets us building again.

### CODE REVIEW

**Comment by jshier** [comment]
Strangely, even with these changes, there seems to be some other underlying change that breaks one of my small app projects.

<details><summary>AppFeature</summary>

```swift
@Reducer
struct AppFeature: Reducer {
    @ObservableState
    struct State: Equatable {
        @CasePathable
        @dynamicMemberLookup
        enum UserState: Equatable {
            case signedIn(SignedInFeature.State)
            case signedOut(SignedOutFeature.State)
        }

        var user: UserState = .signedOut(.init())
        @Presents var alert: AlertState<Never>?
    }

    enum Action: Equatable {
        case openURL(URL)
        case signedIn(SignedInFeature.Action)
        case signedOut(SignedOutFeature.Action)
        case alert(PresentationAction<Never>)
        case signOutComplete
    }

    @Dependency(\.networking) var networking
    @Dependency(\.keychain) var keychain

    var body: some Reducer<State, Action> {
        // App Reducer
        Reduce { state, action in
            switch action {
            case .alert:
                return .none
            case let .openURL(url):
                return .run { _ in
                    await networking.handle(callbackURL: url)
                }
            case .signedIn(.logOut(.logOutConfirmed)):
                return .run { send in
                    await networking.signOut()
                    await send(.signOutComplete)
                }
            case .signOutComplete:
                keychain.removeAll()
                state.user = .signedOut(.init())

                return .none
            case .signedIn:
                // Handled by SignedInDomain.
                return .none
            case let .signedOut(.receiveEmployee(employee)):
                state.user = .signedIn(.idle(for: employee))

                return .send(.signedIn(.refreshExpenses))
            case .signedOut:
                // Handled by SignedOutDomain.
                return .none
            }
        }
        // Automatically manage alert state.
        .ifLet(\.$alert, action: \.alert)
        .ifLet(\.user.signedIn, action: \.signedIn, then: SignedInFeature.init)
        .ifLet(\.user.signedOut, action: \.signedOut, then: SignedOutFeature.init)

        // Global Error Reducer
        Reduce { state, action in
            switch action {
            case let .signedOut(.receiveSignIn(.failure(error as any LocalizedError))),
                 let .signedOut(.receiveRawEmployee(_, .failure(error as any LocalizedError))),
                 let .signedIn(.receiveExpenses(.failure(error as any LocalizedError))):
                state.alert = AppFeature.networkErrorAlert(error)
            case .openURL, .signedIn, .signedOut, .alert, .signOutComplete:
                // Handled by other reducers.
                break
            }

            return .none
        }
    }

    static func networkErrorAlert(_ error: any LocalizedError) -> AlertState<Never> {
        let title = "An Error Occurred"
        let message = """
        Sorry, that network call failed due to an error, please try again.

        \(error.errorDescription ?? error.localizedDescription)
        """

        return AlertState {
            TextState(title)
        } message: {
            TextState(message)
        }
    }
}
```

</details>

Which fails to build with:
```
AppFeature.swift:64:16: error: cannot convert value of type 'WritableKeyPath<AppFeature.State, SignedInFeature.State>' to expected argument type 'WritableKeyPath<AppFeature.State, SignedInFeature.State?>'
        .ifLet(\.user.signedIn, action: \.signedIn, then: SignedInFeature.init)
               ^
AppFeature.swift:64:16: note: arguments to generic parameter 'Value' ('SignedInFeature.State' and 'SignedInFeature.State?') are expected to be equal
        .ifLet(\.user.signedIn, action: \.signedIn, then: SignedInFeature.init)
               ^
AppFeature.swift:65:16: error: cannot convert value of type 'WritableKeyPath<AppFeature.State, SignedOutFeature.State>' to expected argument type 'WritableKeyPath<AppFeature.State, SignedOutFeature.State?>'
        .ifLet(\.user.signedOut, action: \.signedOut, then: SignedOutFeature.init)
               ^
AppFeature.swift:65:16: note: arguments to generic parameter 'Value' ('SignedOutFeature.State' and 'SignedOutFeature.State?') are expected to be equal
        .ifLet(\.user.signedOut, action: \.signedOut, then: SignedOutFeature.init)
```
There are some major type checker changes in Swift 6.3, so this may be fallout from that.

**Comment by stephencelis** [comment]
@jshier Can you share a couple bare reducers that reproduce the problem? I can take a look and try incorporating it here.

Edit: Oh I missed the collapsed bit. Assuming that compiles on its own I'll take a look when I'm back at my desk!

**Comment by jshier** [comment]
This should compile with the errors on its own:

```swift
@Reducer
struct TestFeature {
    @ObservableState
    struct State: Equatable {
        @CasePathable
        @dynamicMemberLookup
        enum UserState: Equatable {
            case signedIn(FeatureOne.State)
            case signedOut(FeatureTwo.State)
        }
    
        var user: UserState = .signedOut(.init())
    }

    enum Action {}

    var body: some ReducerOf<Self> {
        Reduce { _, _ in
            return .none
        }
        .ifLet(\.user.signedIn, action: \.signedIn, then: FeatureOne.init)
        .ifLet(\.user.signedOut, action: \.signedOut, then: FeatureTwo.init)
    }
}

@Reducer
struct FeatureOne {}

@Reducer
struct FeatureTwo {}
```
which produces these errors:
```
AppFeature.swift:119:16: error: cannot convert value of type 'WritableKeyPath<TestFeature.State, FeatureOne.State>' to expected argument type 'WritableKeyPath<TestFeature.State, FeatureOne.State?>'
        .ifLet(\.user.signedIn, action: \.signedIn, then: FeatureOne.init)
               ^
AppFeature.swift:119:16: note: arguments to generic parameter 'Value' ('FeatureOne.State' and 'FeatureOne.State?') are expected to be equal
        .ifLet(\.user.signedIn, action: \.signedIn, then: FeatureOne.init)
               ^
AppFeature.swift:119:41: error: cannot convert value of type 'KeyPath<Root, Value>' to expected argument type 'AnyCasePath<TestFeature.Action, FeatureOne.Action>'
        .ifLet(\.user.signedIn, action: \.signedIn, then: FeatureOne.init)
                                        ^
AppFeature.swift:119:41: error: cannot infer key path type from context; consider explicitly specifying a root type
        .ifLet(\.user.signedIn, action: \.signedIn, then: FeatureOne.init)
                                        ^
                                         <#Root#>
AppFeature.swift:120:16: error: cannot convert value of type 'WritableKeyPath<TestFeature.State, FeatureTwo.State>' to expected argument type 'WritableKeyPath<TestFeature.State, FeatureTwo.State?>'
        .ifLet(\.user.signedOut, action: \.signedOut, then: FeatureTwo.init)
               ^
AppFeature.swift:120:16: note: arguments to generic parameter 'Value' ('FeatureTwo.State' and 'FeatureTwo.State?') are expected to be equal
        .ifLet(\.user.signedOut, action: \.signedOut, then: FeatureTwo.init)
               ^
AppFeature.swift:120:42: error: cannot convert value of type 'KeyPath<Root, Value>' to expected argument type 'AnyCasePath<TestFeature.Action, FeatureTwo.Action>'
        .ifLet(\.user.signedOut, action: \.signedOut, then: FeatureTwo.init)
                                         ^
AppFeature.swift:120:42: error: cannot infer key path type from context; consider explicitly specifying a root type
        .ifLet(\.user.signedOut, action: \.signedOut, then: FeatureTwo.init)
                                         ^
                                          <#Root#>
```

**Review by mbrandonw — APPROVED** [review]

**Comment by stephencelis** [comment]
@jshier I think this might be a soundness hole that was fixed. I don't think that chained key path was legit. This should work around the issue though:

```swift
Scope(state: \.user, action: \.self) {
  EmptyReducer()
    .ifLet(\.signedIn, action: \.signedIn, then: FeatureOne.init)
    .ifLet(\.signedOut, action: \.signedOut, then: FeatureTwo.init)
}
```

And we do have some major changes to CasePaths coming that should help restore syntax similar to what you originally had.

Going to merge this, though, since it gets at the root issues!

**Comment by jshier** [comment]
@stephencelis That didn't work for me but I'll keep trying. Hopefully the CasePath update can help with the non-Presented reducer case so we can use enum reducers directly.

**Comment by stephencelis** [comment]
@jshier Here's the full snippet of changes required to get things working. My snippet above incorrectly used `ifLet` instead of `ifCaseLet` and was missing the action cases.

```swift
@Reducer
struct TestFeature {
  @ObservableState
  struct State: Equatable {
    @CasePathable
    @dynamicMemberLookup
    enum UserState: Equatable {
      case signedIn(FeatureOne.State)
      case signedOut(FeatureTwo.State)
    }

    var user: UserState = .signedOut(.init())
  }

  enum Action {
    case signedIn(FeatureOne.Action)
    case signedOut(FeatureTwo.Action)
  }

  var body: some ReducerOf<Self> {
    Reduce { _, _ in
      return .none
    }
    Scope(state: \.user, action: \.self) {
      EmptyReducer()
        .ifCaseLet(\.signedIn, action: \.signedIn, then: FeatureOne.init)
        .ifCaseLet(\.signedOut, action: \.signedOut, then: FeatureTwo.init)
    }
  }
}

@Reducer
struct FeatureOne {}

@Reducer
struct FeatureTwo {}
```
